### ISSUE TITLE
Issue when building SonataAdmin bundle docs

### ISSUE THREAD

**Issue by javiereguiluz** [symfony-tools/docs-builder#89]
Here's the detailed log:

```
Error when building SonataAdminBundle docs
Warning: Undefined array key -1

  #0 vendor/doctrine/rst-parser/lib/Nodes/TableNode.php(188): Doctrine\RST\Nodes\TableNode->compileSim
  pleTable()
  #1 vendor/doctrine/rst-parser/lib/Nodes/TableNode.php(148): Doctrine\RST\Nodes\TableNode->compile()
  #2 vendor/doctrine/rst-parser/lib/Parser/DocumentParser.php(511): Doctrine\RST\Nodes\TableNode->fina
  lize(Object(Doctrine\RST\Parser))
  #3 vendor/doctrine/rst-parser/lib/Parser/DocumentParser.php(315): Doctrine\RST\Parser\DocumentParser
  ->flush()
  #4 vendor/doctrine/rst-parser/lib/Parser/DocumentParser.php(205): Doctrine\RST\Parser\DocumentParser
  ->parseLine('')
  #5 vendor/doctrine/rst-parser/lib/Parser/DocumentParser.php(145): Doctrine\RST\Parser\DocumentParser
  ->parseLines('\nField Types\n==...')
  #6 vendor/doctrine/rst-parser/lib/Parser.php(178): Doctrine\RST\Parser\DocumentParser->parse('Field
  Types\n===...')
  #7 vendor/doctrine/rst-parser/lib/Parser.php(162): Doctrine\RST\Parser->parseLocal('Field Types\n===
  ...')
  #8 vendor/doctrine/rst-parser/lib/Parser.php(200): Doctrine\RST\Parser->parse('Field Types\n===...')
  #9 vendor/doctrine/rst-parser/lib/Builder/ParseQueueProcessor.php(71): Doctrine\RST\Parser->parseFil
  e('/Users/javier/w...')
  #10 vendor/doctrine/rst-parser/lib/Builder/ParseQueueProcessor.php(59): Doctrine\RST\Builder\ParseQu
  eueProcessor->processFile('reference/field...')
  #11 vendor/doctrine/rst-parser/lib/Builder.php(220): Doctrine\RST\Builder\ParseQueueProcessor->proce
  ss(Object(Doctrine\RST\Builder\ParseQueue))
  #12 vendor/doctrine/rst-parser/lib/Builder.php(157): Doctrine\RST\Builder->parse('/Users/javier/w...
  ', '/Users/javier/w...', Object(Doctrine\RST\Builder\ParseQueue))
  #13 docs-builder/src/DocBuilder.php(26): Doctrine\RST\Builder->build('/Users/javier/w...', '/Users/javi
  er/w...')
  #14 src/Command/BuildBundlesDocCommand.php(187): SymfonyDocsBuilder\DocBuilder->build(Object(Symfony
  DocsBuilder\BuildConfig))
  #15 src/Command/BuildBundlesDocCommand.php(79): App\Command\BuildBundlesDocCommand->buildDoc(Object(
  App\Entity\Bundle), '3.x')
  #16 vendor/symfony/console/Command/Command.php(256): App\Command\BuildBundlesDocCommand->execute(Obj
  ect(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #17 vendor/symfony/console/Application.php(989): Symfony\Component\Console\Command\Command->run(Obje
  ct(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #18 vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Applicati
  on->doRunCommand(Object(App\Command\BuildBundlesDocCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Comp
  onent\Console\Output\ConsoleOutput))
  #19 vendor/symfony/console/Application.php(290): Symfony\Bundle\FrameworkBundle\Console\Application-
  >doRunCommand(Object(App\Command\BuildBundlesDocCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Compone
  nt\Console\Output\ConsoleOutput))
  #20 vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Applicati
  on->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #21 vendor/symfony/console/Application.php(166): Symfony\Bundle\FrameworkBundle\Console\Application-
  >doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #22 bin/console(43): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Inp
  ut\ArgvInput))
  #23 {main}
```

**Comment by javiereguiluz** [comment]
The errors seem related to:

(1) In this file -> https://raw.githubusercontent.com/sonata-project/SonataAdminBundle/3.x/docs/reference/security.rst

The following headless table:

```rst
========================   ======================================================
app.admin.foo              ROLE_APP_ADMIN_FOO_{PERMISSION}
my.blog.admin.foo_bar      ROLE_MY_BLOG_ADMIN_FOO_BAR_{PERMISSION}
App\\Admin\\FooAdmin       ROLE_APP\\ADMIN\\FOOADMIN_{PERMISSION}
========================   ======================================================
```

(2) In this file -> https://raw.githubusercontent.com/sonata-project/SonataAdminBundle/3.x/docs/reference/field_types.rst

This table which has blank lines inside some cells:

```rst
======================================  ============================================================
Option                                  Description
======================================  ============================================================
**inline**                              If ``true``, the array will be displayed as a single line,
                                        the whole array and each array level will be wrapped up with square brackets.
                                        If ``false``, the array will be displayed as an unordered list.
                                        For the ``show`` action, the default value is ``true`` and for the ``list`` action
                                        it's ``false``.
**display**                             Define what should be displayed: keys, values or both.
                                        Defaults to ``'both'``.
                                        Available options are: ``'both'``, ``'keys'``, ``'values'``.
**key_translation_domain**              This option determines if the keys should be translated and
                                        in which translation domain.

                                        The values of this option can be ``true`` (use admin
                                        translation domain), ``false`` (disable translation), ``null``
                                        (uses the parent translation domain or the default domain)
                                        or a string which represents the exact translation domain to use.
**value_translation_domain**            This option determines if the values should be translated and
                                        in which translation domain.

                                        The values of this option can be ``true`` (use admin
                                        translation domain), ``false`` (disable translation), ``null``
                                        (uses the parent translation domain or the default domain)
                                        or a string which represents the exact translation domain to use.
======================================  ============================================================
```

**Comment by javiereguiluz** [comment]
I'm closing this one because it was fixed by changing the original docs. I don't care about the headless tables problem because it's very rare to use them ... but the other problem of new lines inside table cells could be a problem in the future. We'll see. Thanks!
